Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 130
Metrics/MethodLength:
  Max: 30
Lint/Debugger:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
GlobalVars:
  AllowedVariables:
    - $browser
