addons:
  hosts:
    - local.bullioncaptial.com
    - local-general-socket.bullioncaptial.com
    - local-main-socket.bullioncaptial.com
    - local-reports-socket.bullioncaptial.com
sudo: required
dist: trusty
services:
  - docker
before_install:
  # Host file entries to make local.bullioncapital.com available to test suite
  - echo "127.0.0.1 local.bullioncapital.com" | sudo tee --append /etc/hosts
  - echo "127.0.0.1 local-general-socket.bullioncapital.com" | sudo tee --append /etc/hosts
  - echo "127.0.0.1 local-main-socket.bullioncapital.com" | sudo tee --append /etc/hosts
  - echo "127.0.0.1 local-reports-reports.bullioncapital.com" | sudo tee --append /etc/hosts

  # Update Docker
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

  # Install compatible docker compose
  - sudo curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

  # Docker login to make images available
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t testing .
  - docker swarm init

  # Node
  - nvm install 8.9
  - nvm use 8.9

  # Add AWS Creds
  - mkdir ~/.aws
  - echo "[default]" >> ~/.aws/credentials
  - echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
  - echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

  # Orc Clone
  - git clone git@github.com:bullioncapital/orc.git
  - cd orc && npm i && npm run compile && npm run local-noninteractive

  # Sleep for a minute
  - echo "sleeping to let exchange stabalise"
  - sleep 60

script:
  - docker run --net=host testing
branches:
  only:
    - integration
notifications:
  email:
    recipients:
      - sam.jeston@abx.com
    on_success: change
    on_failure: always
